pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                // Change directory to the subfolder 'PharmaCareServer'
                dir('PharmaCareServer') {
                    // Run Maven build commands
                    sh 'mvn clean install'
                }
            }
        }
	stage('Deploy') {
            steps {
		// Wrap the step you want to ignore failures for in a try-catch blocks
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    sh 'chmod +x jenkins/script.sh'
		    sh 'chmod +x jenkins/server.sh'
		    sh 'chmod +x jenkins/client.sh'
		    sh './jenkins/script.sh'
		    sh './jenkins/server.sh'
		    sh './jenkins/client.sh'
                }             
            }
        }	
    }
}
